legit: Upgrade to latest ref
To incorporate fix for a scrolling quirk.

---

I made this commit from 2f46f8696c8f05b307f1faab7fac9a349604d2c8
because updates to Home Manager (bc153fd8e31741871cbb87e5f06c695b6e5e2b95)
broke fundamental code or something somewhere and errors like this:

```
error:
       … while evaluating a branch condition
         at /nix/store/k8lkqr2w6s5khwzhayly1bb2m8225n5c-source/lib/lists.nix:142:18:
          141|       len = length list;
          142|       fold' = n: if n == len then nul else op (elemAt list n) (fold' (n + 1));
             |                  ^
          143|     in

       … while calling the 'length' builtin
         at /nix/store/k8lkqr2w6s5khwzhayly1bb2m8225n5c-source/lib/lists.nix:141:13:
          140|     let
          141|       len = length list;
             |             ^
          142|       fold' = n: if n == len then nul else op (elemAt list n) (fold' (n + 1));

       (stack trace truncated; use '--show-trace' to show the full, detailed trace)

       error: expected a set but found null: null
```

Of course, showing stack trace emits unhelpful non-descriptive unguarded
internal functions.

Searched by the error message and got nothing.
Took a look at the Nix's source code and got nothing.
Checked stack trace lines for my source code and got nothing.

Untyped and unguarded function, with obscured module name.
It seems Nix stack trace cannot show the bottom of stack trace.
Maybe the module system is the culprit? Either way, this error feedback
mechanism definitely not working.
This is literally the worst developer experience I've ever had.

Perhaps I should check out Guix. I can't imagine Scheme being worse than
Nix the language. (except excessive parentheses)